/**
 * The `_redirects` file body, on its own so that it can be used without a
 * database. scripts/redirects.mjs imports db.mjs, which refuses to load without
 * SUPABASE_DB_URL — and CI, which has no database, still has to write the file
 * from the committed data/redirects.json.
 */

export function formatRedirects(redirects) {
  const header = [
    '# Generated by scripts/emit-data.mjs from the retired rows in public.slugs.',
    '# Never edit by hand: rename a place in the database and rebuild.',
    '',
  ];
  return [...header, ...redirects.map((r) => `${r.from} ${r.to} 301`), ''].join('\n');
}
