/**
 * The `_redirects` file body, on its own so that it can be used without a
 * database. scripts/redirects.mjs imports db.mjs, which refuses to load without
 * SUPABASE_DB_URL — and CI, which has no database, still has to write the file
 * from the committed data/redirects.json.
 */

export function formatRedirects(redirects) {
  const header = [
    '# Generated by scripts/emit-data.mjs from the retired rows in public.slugs.',
    '# Never edit by hand: rename a place in the database and rebuild.',
    '',
  ];
  // The bare root. Astro's own `redirects` config writes a meta-refresh page
  // with a robots noindex for `/`, which is the one address Google reads the
  // site name from (docs/reference/seo-research/01-what-google-says.md §3).
  // A real 301 hands Google the German home page as the home page instead.
  const root = ['# The bare root goes to the default locale as a real redirect, not a meta-refresh.', '/ /de/ 301', ''];
  // Each retired address also without its final slash. Cloudflare matches a
  // rule exactly, and only adds the slash for a file that exists — so a
  // retired address typed or pasted without it was a 404 (2026-09-28).
  const lines = redirects.flatMap((r) => {
    const rule = `${r.from} ${r.to} 301`;
    return r.from.endsWith('/') && r.from.length > 1 && !r.from.includes('*')
      ? [rule, `${r.from.slice(0, -1)} ${r.to} 301`]
      : [rule];
  });
  return [...header, ...root, ...lines, ''].join('\n');
}
