-- The last ten of the 92 Swiss descriptions. Eight are the listings a second
-- agent confirmed are real (intake/descriptions/checked-doubtful.json),
-- NerdYartist stays listed and says plainly it is an artists' market selling
-- new work (Delfim, 2026-10-08), and Brocante de Rive Nyon is written now its
-- organiser is settled. Same rules and checks as 20261008140000.

begin;

create temporary table new_description (slug text, locale text, value text) on commit drop;
insert into new_description values
  ($t$boutique-kleider-flohmarkt-wbz-reinach$t$, 'en', $t$Clothes, bags and shoes are all you'll find here: this is the WBZ's small fashion flea market. The WBZ in Reinach has worked for people with disabilities since 1975, and its flea-market team runs this one. Crockery, pictures and the rest wait for the big four-day WBZ-Flohmarkt, held in the same building. Restaurant Piazza, the WBZ's own, is in the house.$t$),
  ($t$boutique-kleider-flohmarkt-wbz-reinach$t$, 'de', $t$Kleider, Taschen und Schuhe – mehr gibt es hier nicht: Das ist der kleine Modeflohmarkt des WBZ. Das WBZ in Reinach setzt sich seit 1975 für Menschen mit Behinderung ein, und sein Flohmarkt-Team führt auch diesen Markt durch. Geschirr, Bilder und alles andere gibt es am grossen viertägigen WBZ-Flohmarkt im selben Haus. Das hauseigene Restaurant Piazza ist gleich da.$t$),
  ($t$boutique-kleider-flohmarkt-wbz-reinach$t$, 'fr', $t$Vêtements, sacs et chaussures, c'est tout ce que vous trouverez ici : c'est le petit marché aux puces mode du WBZ. Le WBZ, à Reinach, s'engage depuis 1975 pour les personnes en situation de handicap, et c'est son équipe du marché aux puces qui organise celui-ci. Vaisselle, tableaux et tout le reste attendent le grand WBZ-Flohmarkt de quatre jours, dans le même bâtiment. Le Restaurant Piazza, celui du WBZ, est sur place.$t$),
  ($t$boutique-kleider-flohmarkt-wbz-reinach$t$, 'it', $t$Vestiti, borse e scarpe, e nient'altro: è il piccolo mercatino della moda del WBZ. Il WBZ di Reinach lavora per le persone con disabilità dal 1975, e questo mercatino lo organizza la sua squadra del Flohmarkt. Stoviglie, quadri e tutto il resto aspettano il grande WBZ-Flohmarkt di quattro giorni, nello stesso edificio. Il Restaurant Piazza, quello del WBZ, è in casa.$t$),
  ($t$brocante-17-terra-geneve$t$, 'en', $t$17 Terra is a ground-floor pop-up shop in Eaux-Vives that hands its space to a new event every week or so; this brocante is one of them. Professional dealers bring furniture, mirrors, paintings, jewellery, lamps, tableware and decorative pieces. The tram stops a few steps from the door.$t$),
  ($t$brocante-17-terra-geneve$t$, 'de', $t$17 Terra ist ein Pop-up-Laden im Erdgeschoss in Eaux-Vives, in dem sich die Anlässe etwa wochenweise abwechseln; diese Brocante ist einer davon. Professionelle Händlerinnen und Händler bringen Möbel, Spiegel, Bilder, Schmuck, Lampen, Tischkultur und Dekoobjekte mit. Das Tram hält ein paar Schritte vor der Tür.$t$),
  ($t$brocante-17-terra-geneve$t$, 'fr', $t$17 Terra est une boutique éphémère en rez-de-chaussée aux Eaux-Vives, où les événements se relaient à peu près chaque semaine ; cette brocante en fait partie. Des marchands professionnels y apportent mobilier, miroirs, tableaux, bijoux, luminaires, arts de la table et objets décoratifs. Le tram s'arrête à deux pas de la porte.$t$),
  ($t$brocante-17-terra-geneve$t$, 'it', $t$17 Terra è un negozio temporaneo al pianterreno, a Eaux-Vives, dove gli eventi si danno il cambio più o meno ogni settimana; questa brocante è uno di questi. Commercianti professionisti portano mobili, specchi, quadri, gioielli, lampade, articoli per la tavola e oggetti decorativi. Il tram ferma a due passi dalla porta.$t$),
  ($t$flohmarkt-am-see-wollishofen-zuerich$t$, 'en', $t$Nobody books a pitch here: people turn up with their own things and lay them out on the lawn at the GZ Wollishofen. The community centre runs it with a team of volunteers. It happens only in dry weather, and whether it's on is posted on the GZ website, Instagram and Facebook a day or two before.$t$),
  ($t$flohmarkt-am-see-wollishofen-zuerich$t$, 'de', $t$Reservieren kann man hier nichts: Die Leute kommen mit ihren eigenen Sachen und legen sie auf der Wiese beim GZ Wollishofen aus. Das Gemeinschaftszentrum führt den Markt mit einem Team von Freiwilligen durch. Er findet nur bei trockenem Wetter statt; ob er durchgeführt wird, siehst du ein bis zwei Tage vorher auf der Website des GZ, auf Instagram und Facebook.$t$),
  ($t$flohmarkt-am-see-wollishofen-zuerich$t$, 'fr', $t$Ici, personne ne réserve sa place : on arrive avec ses propres affaires et on les étale sur la pelouse du GZ Wollishofen. Le centre de quartier l'organise avec une équipe de bénévoles. Le marché n'a lieu que par temps sec ; un ou deux jours avant, le site du GZ, Instagram et Facebook annoncent s'il est maintenu.$t$),
  ($t$flohmarkt-am-see-wollishofen-zuerich$t$, 'it', $t$Qui nessuno prenota un posto: la gente arriva con le proprie cose e le stende sul prato del GZ Wollishofen. Il centro di quartiere lo organizza con un gruppo di volontari. Si tiene solo con il tempo asciutto; uno o due giorni prima, il sito del GZ, Instagram e Facebook ti dicono se si fa.$t$),
  ($t$flohmarkt-schlieren-herbstmarkt$t$, 'en', $t$Schlieren's schoolchildren sell their old toys and books here, laid out on plastic sheets. The Kulturkommission Schlieren runs it and sets the spot in the town centre each year. If it rains, the children's market moves into the underground car park at the Stadthaus. In past years an autumn market has run alongside, with Apfelchüechli, Zopf, crafts and stands where local clubs show what they do.$t$),
  ($t$flohmarkt-schlieren-herbstmarkt$t$, 'de', $t$Hier verkaufen Schlieremer Schulkinder ihre alten Spielsachen und Bücher, ausgelegt auf Plastikblachen. Die Kulturkommission Schlieren organisiert den Markt und legt den Platz im Zentrum jedes Jahr neu fest. Bei Regen zieht der Kinderflohmarkt in die Tiefgarage beim Stadthaus. In früheren Jahren lief daneben ein Herbstmarkt mit Apfelchüechli, Zopf, Kunsthandwerk und Infoständen, an denen Schlieremer Vereine ihre Arbeit zeigen.$t$),
  ($t$flohmarkt-schlieren-herbstmarkt$t$, 'fr', $t$Les écoliers de Schlieren y vendent leurs vieux jouets et leurs livres, étalés sur des bâches. La Kulturkommission Schlieren l'organise et fixe chaque année l'emplacement au centre-ville. S'il pleut, le marché des enfants descend dans le parking souterrain du Stadthaus. Les années précédentes, un marché d'automne se tenait à côté, avec Apfelchüechli, tresse, artisanat et des stands où les sociétés locales présentent leurs activités.$t$),
  ($t$flohmarkt-schlieren-herbstmarkt$t$, 'it', $t$Qui gli scolari di Schlieren vendono i loro vecchi giocattoli e libri, stesi su teloni di plastica. La Kulturkommission Schlieren lo organizza e sceglie ogni anno il posto in centro. Se piove, il mercatino dei bambini si sposta nell'autorimessa sotterranea dello Stadthaus. Negli anni passati, accanto c'era anche un mercato d'autunno, con Apfelchüechli, treccia, artigianato e stand dove le associazioni del posto raccontano cosa fanno.$t$),
  ($t$hyper-bazar-la-chaux-de-fonds$t$, 'en', $t$Hyper Bazar spreads 90 stalls over five zones around the Place de la Carmagnole. Second-hand clothes fill the Passage Guillaume-Ritter; professional dealers with old things, books and vintage take the Passage Léopold-Robert. On the Place de l'Hôtel de Ville people sell straight from their car boots, private sellers clear out everyday things on the Carmagnole itself, and makers bring handmade goods and small labels to the Passage du Centre. Children get their own corner to sell toys, and there's an open stage. The fruit and vegetable market is close by. Parking de la Ronde is five minutes on foot; the nearest bus stop is Grande Fontaine.$t$),
  ($t$hyper-bazar-la-chaux-de-fonds$t$, 'de', $t$Hyper Bazar verteilt 90 Stände auf fünf Zonen rund um die Place de la Carmagnole. Secondhand-Kleider hängen in der Passage Guillaume-Ritter, professionelle Händler mit alten Sachen, Büchern und Vintage stehen in der Passage Léopold-Robert. Auf der Place de l'Hôtel de Ville wird direkt aus dem Kofferraum verkauft, auf der Carmagnole selbst räumen Privatleute aus, und in der Passage du Centre zeigen Kreative Handgemachtes und kleine Labels. Kinder haben eine eigene Ecke für ihre Spielsachen, dazu gibt es eine offene Bühne. Der Früchte- und Gemüsemarkt ist gleich in der Nähe. Vom Parking de la Ronde sind es fünf Minuten zu Fuss; die nächste Bushaltestelle heisst Grande Fontaine.$t$),
  ($t$hyper-bazar-la-chaux-de-fonds$t$, 'fr', $t$Hyper Bazar répartit 90 stands en cinq zones autour de la Place de la Carmagnole. Le vide-dressing occupe le Passage Guillaume-Ritter ; au Passage Léopold-Robert, des professionnels proposent objets anciens, livres et vintage. Sur la Place de l'Hôtel de Ville, on vend directement depuis le coffre de la voiture ; sur la Carmagnole même, des particuliers vident leurs placards, et au Passage du Centre, des créateurs présentent du fait main et de petites marques. Les enfants ont leur coin pour vendre leurs jouets, et une scène est ouverte à qui veut jouer. Le marché de fruits et légumes est tout près. Le parking de la Ronde est à cinq minutes à pied ; l'arrêt de bus le plus proche est Grande Fontaine.$t$),
  ($t$hyper-bazar-la-chaux-de-fonds$t$, 'it', $t$Hyper Bazar distribuisce 90 bancarelle in cinque zone attorno alla Place de la Carmagnole. I vestiti di seconda mano stanno nel Passage Guillaume-Ritter; nel Passage Léopold-Robert ci sono commercianti professionisti con oggetti d'epoca, libri e vintage. Sulla Place de l'Hôtel de Ville si vende direttamente dal bagagliaio dell'auto, sulla Carmagnole stessa i privati svuotano gli armadi, e nel Passage du Centre i creativi portano oggetti fatti a mano e piccoli marchi. I bambini hanno un angolo tutto loro per vendere i giocattoli, e c'è un palco aperto. Il mercato di frutta e verdura è lì vicino. Dal Parking de la Ronde sono cinque minuti a piedi; la fermata del bus più vicina è Grande Fontaine.$t$),
  ($t$kinderflohmarkt-gz-heuried$t$, 'en', $t$Kids' things are what's on the tables at the GZ Heuried's flea market, and nothing for grown-ups. Those get their own turn: the same community centre holds two flea markets a year where anything for adults may be sold.$t$),
  ($t$kinderflohmarkt-gz-heuried$t$, 'de', $t$Am Flohmarkt des GZ Heuried liegen Kindersachen auf den Tischen und nichts für Erwachsene. Die haben eigene Termine: Zweimal im Jahr führt das GZ einen eigenen Flohmarkt durch, an dem alles für Erwachsene verkauft werden darf.$t$),
  ($t$kinderflohmarkt-gz-heuried$t$, 'fr', $t$Au marché aux puces du GZ Heuried, il n'y a sur les tables que des affaires d'enfants, rien pour les adultes. Celles-ci ont leur tour ailleurs dans l'année : le même centre de quartier organise deux marchés aux puces par an où tout ce qui concerne les adultes peut se vendre.$t$),
  ($t$kinderflohmarkt-gz-heuried$t$, 'it', $t$Al mercatino del GZ Heuried sui banchi ci sono solo cose per bambini, niente per gli adulti. Quelle hanno il loro turno: lo stesso centro di quartiere organizza due mercatini all'anno dove si può vendere tutto ciò che è per adulti.$t$),
  ($t$kinderflohmarkt-gz-hottingen$t$, 'en', $t$GZ Hottingen puts this one on together with the Quartierverein Hottingen. Each stall is a bedsheet on the ground or a small table that the sellers bring themselves.$t$),
  ($t$kinderflohmarkt-gz-hottingen$t$, 'de', $t$Das GZ Hottingen führt diesen Markt zusammen mit dem Quartierverein Hottingen durch. Ein Stand ist ein Leintuch am Boden oder ein kleiner Tisch, den die Verkäuferinnen und Verkäufer selbst mitbringen.$t$),
  ($t$kinderflohmarkt-gz-hottingen$t$, 'fr', $t$Le GZ Hottingen l'organise avec le Quartierverein Hottingen, l'association du quartier. Chaque stand, c'est un drap posé au sol ou une petite table, apportés par les vendeurs eux-mêmes.$t$),
  ($t$kinderflohmarkt-gz-hottingen$t$, 'it', $t$Il GZ Hottingen lo organizza insieme al Quartierverein Hottingen, l'associazione di quartiere. Ogni bancarella è un lenzuolo steso a terra o un tavolino che chi vende si porta da casa.$t$),
  ($t$les-puces-du-loup-lausanne$t$, 'en', $t$Only people who live on the Plateau de la Blécherette can take a stall – Bois-Gentil, Bossons, Grattapaille and the Plaines-du-Loup – and no professionals. The stalls stand around the Plaines-du-Loup school, and the neighbourhood's restaurants stay open. Bus 1 stops at Bois-Gentil, bus 21 at Grattapaille or Bossons. Parking du Vélodrome is free; Parking du Loup is paid.$t$),
  ($t$les-puces-du-loup-lausanne$t$, 'de', $t$Einen Stand bekommt nur, wer auf dem Plateau de la Blécherette wohnt – in Bois-Gentil, Bossons, Grattapaille oder den Plaines-du-Loup –, und Profis sind nicht zugelassen. Die Stände stehen rund ums Schulhaus Plaines-du-Loup, und die Restaurants im Quartier haben offen. Der Bus 1 hält bei Bois-Gentil, der Bus 21 bei Grattapaille oder Bossons. Das Parking du Vélodrome ist gratis, das Parking du Loup kostet.$t$),
  ($t$les-puces-du-loup-lausanne$t$, 'fr', $t$Seuls les habitants du Plateau de la Blécherette peuvent tenir un stand – Bois-Gentil, Bossons, Grattapaille et les Plaines-du-Loup – et aucun professionnel. Les stands s'installent autour du collège des Plaines-du-Loup, et les restaurants du quartier restent ouverts. Bus 1 arrêt Bois-Gentil, bus 21 arrêt Grattapaille ou Bossons. Le parking du Vélodrome est gratuit, le parking du Loup payant.$t$),
  ($t$les-puces-du-loup-lausanne$t$, 'it', $t$Solo chi abita sul Plateau de la Blécherette può avere una bancarella – Bois-Gentil, Bossons, Grattapaille e le Plaines-du-Loup – e niente professionisti. Le bancarelle stanno attorno alla scuola delle Plaines-du-Loup, e i ristoranti del quartiere restano aperti. Il bus 1 ferma a Bois-Gentil, il 21 a Grattapaille o Bossons. Il Parking du Vélodrome è gratuito, il Parking du Loup a pagamento.$t$),
  ($t$nerdyartist-markthalle-basel$t$, 'en', $t$Not a flea market: NerdYartist is an artists' market, and everything on the tables is new work by the people selling it – pendants, prints, handmade one-offs. The team behind the Markthalle's Nerd Yard flea market runs it, and it has run on the same day as the hall's night flea market.$t$),
  ($t$nerdyartist-markthalle-basel$t$, 'de', $t$Kein Flohmarkt: NerdYartist ist ein Künstlermarkt, und alles auf den Tischen ist neue Arbeit derer, die es verkaufen – Anhänger, Prints, handgemachte Einzelstücke. Organisiert wird er vom Team hinter dem Nerd Yard, einem der Flohmärkte der Markthalle, und er lief schon am selben Tag wie der Nachtflohmarkt in der Halle.$t$),
  ($t$nerdyartist-markthalle-basel$t$, 'fr', $t$Pas un marché aux puces : NerdYartist est un marché d'artistes, et tout ce qui est sur les tables est du travail neuf, fait par ceux qui le vendent – pendentifs, tirages, pièces uniques faites main. L'équipe du Nerd Yard, l'un des marchés aux puces de la Markthalle, l'organise, et il s'est déjà tenu le même jour que le marché aux puces de nuit de la halle.$t$),
  ($t$nerdyartist-markthalle-basel$t$, 'it', $t$Non è un mercatino delle pulci: NerdYartist è un mercato d'artisti, e tutto quello che c'è sui banchi è lavoro nuovo di chi lo vende – ciondoli, stampe, pezzi unici fatti a mano. Lo organizza il team del Nerd Yard, uno dei mercatini della Markthalle, e si è già tenuto lo stesso giorno del mercatino notturno della hall.$t$),
  ($t$brocante-de-rive-nyon$t$, 'en', $t$This brocante spreads through Nyon's Quartier de Rive and along the lakeside quays, and it has been going for more than forty editions. The neighbourhood's own association, the Association pour l'animation du Quartier de Rive, puts it on. The rest of the year, the same association runs the Puces de Nyon, a flea market once a month.$t$),
  ($t$brocante-de-rive-nyon$t$, 'de', $t$Diese Brocante zieht sich durch Nyons Quartier de Rive und den Quais am See entlang, und es gibt sie schon seit über vierzig Ausgaben. Organisiert wird sie vom Quartierverein selbst, der Association pour l'animation du Quartier de Rive. Den Rest des Jahres führt derselbe Verein die Puces de Nyon durch, einen Flohmarkt einmal im Monat.$t$),
  ($t$brocante-de-rive-nyon$t$, 'fr', $t$Cette brocante s'étend dans le Quartier de Rive et le long des quais de Nyon, et elle compte déjà plus de quarante éditions. C'est l'association du quartier, l'Association pour l'animation du Quartier de Rive, qui l'organise. Le reste de l'année, la même association tient les Puces de Nyon, le rendez-vous mensuel des chineurs.$t$),
  ($t$brocante-de-rive-nyon$t$, 'it', $t$Questa brocante si snoda nel Quartier de Rive di Nyon e lungo i quais sul lago, e conta già più di quaranta edizioni. La organizza l'associazione del quartiere, l'Association pour l'animation du Quartier de Rive. Nel resto dell'anno la stessa associazione tiene le Puces de Nyon, un mercatino una volta al mese.$t$);

do $$
declare n int;
begin
  update public.texts t set value = d.value, updated_at = now()
    from public.markets m, new_description d
   where t.entity_type = 'market' and t.entity_id = m.id and t.field = 'description'
     and m.slug = d.slug and t.locale = d.locale;
  get diagnostics n = row_count;
  if n <> 40 then raise exception 'expected 40, got %', n; end if;
end $$;

commit;
